#seata:
#  enabled: true
#  application-id: lx
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      serverAddr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      userName: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 47.96.131.185:8848
#      namespace:
#      userName: "nacos"
#      password: "nacos"

#seata:
#  enabled: true
#  application-id: account-seata-account
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
#  data-source-proxy-mode: AT
#  client:
#    rm:
#      report-success-enable: true
#      table-meta-check-enable: false
#      report-retry-count: 5
#      async-commit-buffer-limit: 10000
#      lock:
#        retry-interval: 10
#        retry-times:    30
#        retry-policy-branch-rollback-on-conflict: true
#    tm:
#      commit-retry-count:   3
#      rollback-retry-count: 3
#      degrade-check: false
#      degrade-check-period: 2000
#      degrade-check-allow-times: 10
#    undo:
#      data-validation: true
#      log-serialization: jackson
#      log-table: undo_log
#    log:
#      exceptionRate: 100
#  service:
#    vgroupMapping:
#      my_test_tx_group: default
#    enable-degrade: false
#    disable-global-transaction: false
#    grouplist:
#      default: 127.0.0.1:8091
#  transport:
#    shutdown:
#      wait: 3
#    thread-factory:
#      boss-thread-prefix: NettyBoss
#      worker-thread-prefix: NettyServerNIOWorker
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-worker: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-worker-thread-prefix: NettyClientWorkerThread
#    type: TCP
#    server: NIO
#    heartbeat: true
#    serialization: seata
#    compressor: none
#    enable-client-batch-send-request: true
#  registry:
#    type: nacos
#    nacos:
#      server-addr: localhost:8848
#      cluster: default
#  config:
#    type: nacos
#    nacos:
#      server-addr: localhost:8848
#      group: SEATA_GROUP


# -----------seata--------------
#seata:
#  enabled: true
#  application-id: storage-server #服务名
#  tx-service-group: default # default是自定义的事务分组名称
#  enable-auto-data-source-proxy: true # 启用自动数据源代理
#  use-jdk-proxy: false
#  service:
#    vgroup-mapping:
#      default: fsp_tx # default是自定义的事务分组名称，fsp_tx是tc注册到注册中心的服务名称
#    #        grouplist:
#    #            default: 127.0.0.1:8091 # 	仅注册中心为file时使用
#    enable-degrade: false # 是否启用降级
#    disable-global-transaction: false # 是否禁用全局事务
#  config:
#    type: file # 配置中心为file模式
#  registry:
#    type: eureka # 注册中心为eureka
#    eureka:
#      weight: 1
#      service-url: http://192.168.173.95:8761/eureka # 注册中心地址

# -----------seata--------------

